# Generated by Django 4.2 on 2025-10-23 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('notesfile', models.FileField(upload_to='Notesdata')),
                ('Desc', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('Approve', 'Approve'), ('Reject', 'Reject')], max_length=50)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.signup')),
            ],
        ),
        migrations.DeleteModel(
            name='notes',
        ),
    ]
