# Generated by Django 4.2 on 2025-10-27 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contacts',
        ),
    ]
