# Generated by Django 4.2 on 2025-10-27 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_contact_delete_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='reach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=25)),
                ('msg', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='contact',
        ),
    ]
