# Generated by Django 4.2 on 2025-10-27 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_reach_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactnew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('msg', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='reach',
        ),
    ]
