# Generated by Django 4.2 on 2025-10-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_contactnew_delete_reach'),
    ]

    operations = [
        migrations.CreateModel(
            name='cntc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('msg', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Contactnew',
        ),
    ]
